In [1]:
import numpy as np
import pandas as pd

from pandas import Series,DataFrame

In [12]:
arr1 = np.arange(9).reshape((3,3))
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
# right concatenate
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [18]:
# bottom concatenate
np.concatenate([arr1,arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
# now with pandas
ser1 = Series([0,1,2], index=['T','R','S'])
ser2 = Series([3,4,5], index=['Q','W','G'])

In [21]:
# bottom concatenate
pd.concat([ser1,ser2])

T    0
R    1
S    2
Q    3
W    4
G    5
dtype: int64

In [23]:
# order by index, separate by value
pd.concat([ser1,ser2], axis=1)

0   1
G NaN   5
Q NaN   3
R   1 NaN
S   2 NaN
T   0 NaN
W NaN   4

In [24]:
#join and user specific axes
pd.concat([ser1,ser2],axis=1,join_axes=[['T','R','S']])

0   1
T  0 NaN
R  1 NaN
S  2 NaN

In [26]:
# concat and label
pd.concat([ser1,ser2], keys=['cat1', 'cat2'])

cat1  T    0
      R    1
      S    2
cat2  Q    3
      W    4
      G    5
dtype: int64

In [27]:
# Along the axis=1 then these Keys become column headers
pd.concat([ser1,ser2],axis=1,keys=['cat1','cat2'])

cat1  cat2
G   NaN     5
Q   NaN     3
R     1   NaN
S     2   NaN
T     0   NaN
W   NaN     4

In [28]:
# now with data frames
df1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])
df2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])
pd.concat([df1,df2])

Q         X         Y         Z
0       NaN  0.275817  1.083808 -0.896088
1       NaN -0.998889 -0.120592  0.205557
2       NaN  0.080343 -0.143572 -0.739882
3       NaN -1.253714 -0.590052 -0.767329
0  1.291570  0.467632 -2.652880       NaN
1 -0.549319 -0.252302 -0.461743       NaN
2  1.513308 -3.019900  0.823916       NaN

In [29]:
# you can also ignore the index and make an unified index for the new DF
pd.concat([df1,df2], ignore_index=True)

Q         X         Y         Z
0       NaN  0.275817  1.083808 -0.896088
1       NaN -0.998889 -0.120592  0.205557
2       NaN  0.080343 -0.143572 -0.739882
3       NaN -1.253714 -0.590052 -0.767329
4  1.291570  0.467632 -2.652880       NaN
5 -0.549319 -0.252302 -0.461743       NaN
6  1.513308 -3.019900  0.823916       NaN

In [ ]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'